/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2compiladores;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author japumarejo
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        DirField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TGramaticas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TPrimSig = new javax.swing.JTextArea();
        InputField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Grid = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("Laboratorio 2");

        DirField.setEditable(false);

        jButton1.setText("Seleccionar archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TGramaticas.setColumns(20);
        TGramaticas.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        TGramaticas.setRows(5);
        jScrollPane1.setViewportView(TGramaticas);

        TPrimSig.setColumns(20);
        TPrimSig.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        TPrimSig.setRows(5);
        jScrollPane2.setViewportView(TPrimSig);

        InputField.setToolTipText("");

        jButton2.setText("Correr");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Grid.setFont(new java.awt.Font("Liberation Mono", 0, 14)); // NOI18N
        Grid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(Grid);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel3.setText("Gramáticas:");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel4.setText("Primeros y siguientes:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel5.setText("Tabla M:");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InputField, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DirField, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(262, 262, 262)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DirField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser FC = new JFileChooser();
        FC.showSaveDialog(null);
        File F = FC.getSelectedFile();
        String Address = F.getAbsolutePath();
        DirField.setText(Address);
        
        TGramaticas.setText(null);
        TPrimSig.setText(null);
        
        ArrayList<Object> data;
        try {
            data = readFile(Address);
            ArrayList<Simbolo> auxNoTerms = (ArrayList<Simbolo>) data.get(0);
            ArrayList<ArrayList<Production>> auxProds = (ArrayList<ArrayList<Production>>) data.get(1);
            getInitGram(auxNoTerms, auxProds);

            TGramaticas.append("Gramatica Inicial \n \n");
            printGram1(initNoTerms, initProds);

            //Inicio Eliminar Recursividad
            for (int i = 0; i < auxNoTerms.size(); i += 2) {
                Simbolo auxNT = auxNoTerms.get(i);
                ArrayList<Production> auxP = auxProds.get(i);
                if(isRecursive(auxNT, auxP)){
                    auxNoTerms.set(i+1, new Simbolo(auxNT + "'", true));
                    ArrayList<ArrayList<Production>> alphaBeta = getAlphaBeta(auxNT, auxP);
                    ArrayList<ArrayList<Production>> newProd = elimRecursive(auxNoTerms.get(i+1), alphaBeta.get(0), alphaBeta.get(1));
                    auxProds.set(i, newProd.get(0));
                    auxProds.set(i+1, newProd.get(1));
                }
            }
            //Fin Eliminar Recursividad

            //Inicio Factorizar
            for (int i = 0; i < auxNoTerms.size(); i++) {
                Simbolo auxNT = auxNoTerms.get(i);
                ArrayList<Production> auxP = auxProds.get(i);
                if(!auxNT.getSimbolo().equals("-")){
                    if(isFactorizable(auxP)){
                        auxNoTerms.set(i+1, new Simbolo(auxNT + "'", true));
                        ArrayList<ArrayList<Production>> newProd = factorize(auxNoTerms.get(i+1), auxP);
                        auxProds.set(i, newProd.get(0));
                        auxProds.set(i+1, newProd.get(1));
                    }
                }
            }
            //Fin Factorizar

            getFinalGram(auxNoTerms, auxProds);

            TGramaticas.append("Gramatica Final \n \n");
            printGram1(noTerms, prods);

            getTerminals();
            setSwitchs();

            System.out.println("Terminales");
            printTerms();

            getPrim();
            getSgte();
            printPrimSgte();

            //defaultPrimSgte1();
            getMTable2();

            //defaultMTable();
            printMTable();
            tableGraphics();
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TablaReconocimiento tr = new TablaReconocimiento(identify(InputField.getText()));
        tr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
                
            }
        });
        
    }
    
    public  final Simbolo EPS = new Simbolo("&", false);
    public  final Simbolo END = new Simbolo("$", false);
    public  ArrayList<Simbolo> initNoTerms;
    public  ArrayList<ArrayList<Production>> initProds;
    public  ArrayList<Simbolo> noTerms;
    public  ArrayList<ArrayList<Production>> prods;
    public  ArrayList<Simbolo> terms;
    public  ArrayList<ArrayList<Simbolo>> primero;
    public  ArrayList<ArrayList<Simbolo>> siguiente;
    public  Production[][] mTable;
    
    //Leer Archivo
    public  ArrayList<Object> readFile(String filepath) throws FileNotFoundException, IOException{
        BufferedReader br = new BufferedReader(new FileReader(filepath));
        ArrayList<Object> data = new ArrayList<>();
        ArrayList<Simbolo> auxNoTerms = new ArrayList<>();
        ArrayList<ArrayList<Production>> auxProds = new ArrayList<>();
        while(br.ready()){
            String line = br.readLine();
            Simbolo term = new Simbolo("" + line.charAt(0), true);
            String auxP = line.substring(3, line.length());
            Production prod = new Production();
            for (int i = 0; i < auxP.length(); i++) {
                prod.agregarSym(new Simbolo("" + auxP.charAt(i), false));
            }
            if(!arrayContains(auxNoTerms, term)){
                auxNoTerms.add(term);
                auxNoTerms.add(new Simbolo("-", false));
                auxProds.add(new ArrayList<>());
                auxProds.add(new ArrayList<>());
            }
            auxProds.get(auxNoTerms.indexOf(symbolOf(auxNoTerms, term))).add(prod);
        }
        data.add(auxNoTerms);
        data.add(auxProds);
        return data;
    }
    
    //Obtener Gramatica Inicial
    public  void getInitGram(ArrayList<Simbolo> noTerms, ArrayList<ArrayList<Production>> prods){
        initNoTerms = new ArrayList<>();
        initProds = new ArrayList<>();
        for (int i = 0; i < noTerms.size(); i++) {
            if(!noTerms.get(i).getSimbolo().equals("-")){
                initNoTerms.add(noTerms.get(i));
                initProds.add(prods.get(i));
            }
        }
    }
    
    //Obtener Gramatica Final
    public  void getFinalGram(ArrayList<Simbolo> noTerm, ArrayList<ArrayList<Production>> prod){
        noTerms = new ArrayList<>();
        prods = new ArrayList<>();
        for (int i = 0; i < noTerm.size(); i++) {
            if(!noTerm.get(i).getSimbolo().equals("-")){
                noTerms.add(noTerm.get(i));
                prods.add(prod.get(i));
            }
        }
    }
    
    //Obtener Terminales
    public  void getTerminals(){
        terms = new ArrayList<>();
        for (ArrayList<Production> prod : prods) {
            for (Production prod1 : prod) {
                for (Simbolo symb : prod1.getProd()) {
                    if(!arrayContains(noTerms, symb) && !symb.getSimbolo().equals(EPS.getSimbolo()) && !arrayContains(terms, symb)){
                        terms.add(symb);
                    }
                }
            }
        }
        terms.add(END);
    }
    
    //Set Simbolo.NoTerm
    public  void setSwitchs(){
        for (ArrayList<Production> prod : prods) {
            for (Production prod1 : prod) {
                for (int i = 0; i < prod1.getProd().size(); i++) {
                    if(arrayContains(noTerms, prod1.getSimbolo(i))){
                        prod1.getSimbolo(i).setNoTerminal(true);
                    }
                }
            }
        }
    }
    
    //Imprimir Terminales
    public  void printTerms(){
        String out = "[";
        for (int i = 0; i < terms.size()-1; i++) {
            out += terms.get(i).getSimbolo() + ", ";
        }
        out += terms.get(terms.size()-1).getSimbolo() + "]";
        System.out.println(out + "\n");
    }
    
    //Imprimir Gramatica V1
    public  void printGram1(ArrayList<Simbolo> noTerms, ArrayList<ArrayList<Production>> prods){
        for (int i = 0; i < noTerms.size(); i++) {
            String out;
            if(noTerms.get(i).getSimbolo().length() > 1){
                out = noTerms.get(i).getSimbolo() + " -> ";
            }else{
                out = noTerms.get(i).getSimbolo() + "  -> ";
            }
            for (int j = 0; j < prods.get(i).size()-1; j++) {
                out += prods.get(i).get(j).toString() + " | ";
            }
            out += prods.get(i).get(prods.get(i).size()-1).toString();
            TGramaticas.append(out+"\n");
        }
        TGramaticas.append("\n");
    }
    
    //Imprimir Gramatica V2
    public  void printGram2(ArrayList<Simbolo> noTerms, ArrayList<ArrayList<Production>> prods){
        for (int i = 0; i < noTerms.size(); i++) {
            for (int j = 0; j < prods.get(i).size(); j++) {
                System.out.println(noTerms.get(i).getSimbolo() + " -> " + prods.get(i).get(j).toString());
            }
        }
        System.out.println("");
    }
    
    //Array Contains
    public  boolean arrayContains(ArrayList<Simbolo> noTerms, Simbolo term){
        for (Simbolo noTerm : noTerms) {
            if(term.getSimbolo().equals(noTerm.getSimbolo())){
                return true;
            }
        }
        return false;
    }
    
    //Real Simbolo Of
    public  Simbolo symbolOf(ArrayList<Simbolo> noTerms, Simbolo term){
        for (Simbolo noTerm : noTerms) {
            if(term.getSimbolo().equals(noTerm.getSimbolo())){
                return noTerm;
            }
        }
        return EPS;
    }
    
    //Es Recursiva Izquierda
    public  boolean isRecursive(Simbolo noTerm, ArrayList<Production> prods){
        for (Production prod : prods) {
            Simbolo first = prod.getPrimero();
            if(first.getSimbolo().equals(noTerm.getSimbolo())){
                return true;
            }
        }
        return false;
    }
    
    //Obtener Alpha y Beta para Recursividad
    public  ArrayList<ArrayList<Production>> getAlphaBeta(Simbolo noTerm, ArrayList<Production> prods){
        ArrayList<ArrayList<Production>> data = new ArrayList<>();
        ArrayList<Production> alpha = new ArrayList<>();
        ArrayList<Production> beta = new ArrayList<>();
        for (Production prod : prods) {
            Simbolo first = prod.getPrimero();
            if(first.getSimbolo().equals(noTerm.getSimbolo())){
                Production auxP = new Production();
                for (int i = 1; i < prod.getProd().size(); i++) {
                    auxP.agregarSym(prod.getSimbolo(i)); //Qui
                }
                alpha.add(auxP);
            }else{
                beta.add(prod);
            }
        }
        data.add(alpha);
        data.add(beta);
        return data;
    }
    
    //Eliminar Recursividad Basica
    public  ArrayList<ArrayList<Production>> elimRecursive(Simbolo noTerm, ArrayList<Production> alpha, ArrayList<Production> beta){
        ArrayList<ArrayList<Production>> data = new ArrayList<>();
        ArrayList<Production> prods1 = new ArrayList<>();
        ArrayList<Production> prods2 = new ArrayList<>();
        for (Production b : beta) {
            Production auxB = new Production();
            for (Simbolo symb : b.getProd()) {
                if(!symb.getSimbolo().equals(EPS.getSimbolo())){
                    auxB.agregarSym(symb);
                }
            }
            auxB.agregarSym(noTerm);
            prods1.add(auxB);
        }
        for (Production a : alpha) {
            a.agregarSym(noTerm);
            prods2.add(a);
        }
        Production epsP = new Production();
        epsP.agregarSym(EPS);
        prods2.add(epsP);
        data.add(prods1);
        data.add(prods2);
        return data;
    }
    
    //Es Factorizable
    public  boolean isFactorizable(ArrayList<Production> prods){
        for (int i = 0; i < prods.size(); i++) {
            for (int j = i+1; j < prods.size(); j++) {
                if(prods.get(i).getPrimero().getSimbolo().equals(prods.get(j).getPrimero().getSimbolo())){
                    return true;
                }
            }
        }
        return false;
    }
    
    //Obtener Prefijo Inicial
    public  Simbolo getInitPrefix(ArrayList<Production> prods){
        for (int i = 0; i < prods.size(); i++) {
            for (int j = i+1; j < prods.size(); j++) {
                if(prods.get(i).getPrimero().getSimbolo().equals(prods.get(j).getPrimero().getSimbolo())){
                    return prods.get(i).getPrimero();
                }
            }
        }
        return EPS;
    }
    
    //Existe Siguiente Prefijo
    public  boolean nextPrefix(ArrayList<Production> alpha, int index){
        for (int i = 0; i < alpha.size()-1; i++) {
            if(!alpha.get(i).getSimbolo(index).getSimbolo().equals(alpha.get(i+1).getSimbolo(index).getSimbolo())){
                return false;
            }
        }
        return true;
    }
    
    //Factorizacion Basica
    public  ArrayList<ArrayList<Production>> factorize(Simbolo noTerm, ArrayList<Production> prods){
        ArrayList<ArrayList<Production>> data = new ArrayList<>();
        ArrayList<Production> prods1 = new ArrayList<>();
        ArrayList<Production> prods2 = new ArrayList<>();
        ArrayList<Production> alpha = new ArrayList<>();
        ArrayList<Production> gamma = new ArrayList<>();
        Simbolo prefix = getInitPrefix(prods);
        int min = Integer.MAX_VALUE;
        for (Production prod : prods) {
            if(prefix.getSimbolo().equals(prod.getPrimero().getSimbolo())){
                alpha.add(prod);
                if(prod.getProd().size() < min){
                    min = prod.getProd().size();
                }
            }else{
                gamma.add(prod);
            }
        }
        boolean sw = true;
        int index = 1;
        Production prefixProd = new Production();
        prefixProd.agregarSym(prefix);
        while (sw && index < min) {
            if(nextPrefix(alpha, index)){
                prefixProd.agregarSym(alpha.get(0).getSimbolo(index));
            }else{
                sw = false;
            }
            index++;
        }
        for (Production alpha1 : alpha) {
            if(alpha1.getProd().size() == prefixProd.getProd().size()){
                Production epsP = new Production();
                epsP.agregarSym(EPS);
                prods2.add(epsP);
            }else{
                Production auxP = new Production();
                for (int i = prefixProd.getProd().size(); i < alpha1.getProd().size(); i++) {
                    auxP.agregarSym(alpha1.getSimbolo(i)); //Qui
                }
                prods2.add(auxP);
            }
        }
        prefixProd.agregarSym(noTerm);
        prods1.add(prefixProd);
        for (Production gamma1 : gamma) {
            prods1.add(gamma1);
        }
        data.add(prods1);
        data.add(prods2);
        return data;
    }
    
    //Obtener Primeros
    public  void getPrim(){
        primero = new ArrayList<>();
        int n = noTerms.size();
        for (int i = 0; i < n; i++) {
            primero.add(new ArrayList<>());
        }
        for (int i = 0; i < n; i++) {
            ArrayList<Simbolo> aux = getPrimNoTerm(prods.get(i));
            for (Simbolo aux1 : aux) {
                primero.get(i).add(aux1);
            }
        }
    }
    
    //Obtener el Primero de un No Terminal
    public  ArrayList<Simbolo> getPrimNoTerm(ArrayList<Production> prodNT){
        ArrayList<Simbolo> result = new ArrayList<>();
        for (Production prod : prodNT) {
            boolean sw = false;
            int i = 0;
            while(!sw && i < prod.getProd().size()){
                ArrayList<Simbolo> aux = new ArrayList<>();
                if(prod.getSimbolo(i).isNoTerminal()){
                    ArrayList<Production> a = prods.get(noTerms.indexOf(symbolOf(noTerms, prod.getSimbolo(i))));
                    aux = getPrimNoTerm(a);
                    if(!arrayContains(aux, EPS)){
                        sw = true;
                    }
                }else{
                    sw = true;
                    aux.add(prod.getSimbolo(i));
                }
                i++;
                result = union(result, aux);
            }
        }
        return result;
    }
    
    //Obtener Siguientes
    public  void getSgte(){
        siguiente = new ArrayList<>();
        int n = noTerms.size();
        for (int i = 0; i < n; i++) {
            siguiente.add(new ArrayList<>());
        }
        siguiente.get(0).add(END);
        for (int i = 0; i < 2; i++) {
            rule2();
            rule3i();
            rule3ii();
        }
    }
    
    //Regla 2 (Arreglar?)
    public  void rule2(){
        for (ArrayList<Production> prod : prods) {
            for (Production prod1 : prod) {
                int noT = 0;
                ArrayList<Integer> indexs = new ArrayList<>();
                for (int i = 0; i < prod1.getProd().size(); i++) {
                    if(prod1.getSimbolo(i).isNoTerminal()){
                        noT++;
                        indexs.add(i);
                    }
                }
                for (int i = 0; i < noT; i++) {
                    int index = indexs.get(i);
                    Simbolo noTerm = prod1.getSimbolo(index);
                    if(index != prod1.getProd().size() - 1){
                        Production beta = new Production();
                        for (int j = index + 1; j < prod1.getProd().size(); j++) {
                            beta.agregarSym(prod1.getSimbolo(j));
                        }
                        ArrayList<Simbolo> aux1 = primProd(beta);
                        for (Simbolo aux11 : aux1) {
                            if(!aux11.getSimbolo().equals(EPS.getSimbolo()) && !arrayContains(siguiente.get(noTerms.indexOf(symbolOf(noTerms, noTerm))), aux11)){
                                siguiente.get(noTerms.indexOf(symbolOf(noTerms, noTerm))).add(aux11);
                            }
                        }
                        while(beta.getProd().size() != 1 && !aux1.isEmpty() && arrayContains(aux1, EPS)){
                            beta.getProd().remove(0);
                            aux1 = primProd(beta);
                            for (Simbolo aux11 : aux1) {
                                if(!aux11.getSimbolo().equals(EPS.getSimbolo()) && !arrayContains(siguiente.get(noTerms.indexOf(symbolOf(noTerms, noTerm))), aux11)){
                                    siguiente.get(noTerms.indexOf(symbolOf(noTerms, noTerm))).add(aux11);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    //Regla 3i
    public  void rule3i(){
        for (int i = 0; i < prods.size(); i++) {
            ArrayList<Production> prod = prods.get(i);
            for (Production prod1 : prod) {
                Simbolo last = prod1.getUltimo();
                if(last.isNoTerminal()){
                    for (Simbolo symb: siguiente.get(i)) {
                        if(!arrayContains(siguiente.get(noTerms.indexOf(symbolOf(noTerms, last))), symb)){
                            siguiente.get(noTerms.indexOf(symbolOf(noTerms, last))).add(symb);
                        }
                    }
                }
            }
        }
    }
    
    //Regla 3ii (Arreglar? (Verify))
    public  void rule3ii(){
        for (int i = 0; i < prods.size(); i++) {
            ArrayList<Production> prod = prods.get(i);
            for (Production prod1 : prod) {
                int noT = 0;
                ArrayList<Integer> indexs = new ArrayList<>();
                for (int j = 0; j < prod1.getProd().size(); j++) {
                    if(prod1.getSimbolo(j).isNoTerminal()){
                        noT++;
                        indexs.add(j);
                    }
                }
                for (int j = 0; j < noT; j++) {
                    int index = indexs.get(j);
                    Simbolo noTerm = prod1.getSimbolo(index);
                    if(index != prod1.getProd().size() - 1){
                        Production beta = new Production();
                        for (int k = index + 1; k < prod1.getProd().size(); k++) {
                            beta.agregarSym(prod1.getSimbolo(k));
                        }
                        ArrayList<Simbolo> aux1 = primProd(beta);
                        if(arrayContains(aux1, EPS)){
                            if(verifySgte(beta)){
                                for (Simbolo symb: siguiente.get(i)) {
                                    if(!arrayContains(siguiente.get(noTerms.indexOf(symbolOf(noTerms, noTerm))), symb)){
                                        siguiente.get(noTerms.indexOf(symbolOf(noTerms, noTerm))).add(symb);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    //Union de ArrayList<Symbol>
    public  ArrayList<Simbolo> union(ArrayList<Simbolo> arr1, ArrayList<Simbolo> arr2){
        ArrayList<Simbolo> result = new ArrayList<>();
        for (Simbolo arr11 : arr1) {
            result.add(arr11);
        }
        for (Simbolo arr21 : arr2) {
            if(!arrayContains(result, arr21)){
                result.add(arr21);
            }
        }
        return result;
    }
    
    //Imprimir Primero y Siguiente
    public  void printPrimSgte(){
        int n = noTerms.size();
        TPrimSig.append("Primeros \n \n");
        for (int i = 0; i < n; i++) {
            String out;
            if(noTerms.get(i).getSimbolo().length() > 1){
                out = "P(" + noTerms.get(i).getSimbolo() + ") = [";
            }else{
                out = "P(" + noTerms.get(i).getSimbolo() + ")  = [";
            }
            
            for (int j = 0; j < primero.get(i).size()-1; j++) {
                out += primero.get(i).get(j).getSimbolo() + ", ";
            }
            out += primero.get(i).get(primero.get(i).size()-1) + "]";
            TPrimSig.append(out+"\n");
        }
        TPrimSig.append("\nSiguientes \n \n");
        for (int i = 0; i < n; i++) {
            String out;
            if(noTerms.get(i).getSimbolo().length() > 1){
                out = "S(" + noTerms.get(i).getSimbolo() + ") = [";
            }else{
                out = "S(" + noTerms.get(i).getSimbolo() + ")  = [";
            }
            
            for (int j = 0; j < siguiente.get(i).size()-1; j++) {
                out += siguiente.get(i).get(j).getSimbolo() + ", ";
            }
            out += siguiente.get(i).get(siguiente.get(i).size()-1) + "]";
            TPrimSig.append(out+"\n");
        }
        TPrimSig.append("\n");
    }
    
    //Obtener el Primero de una Produccion
    public  ArrayList<Simbolo> primProd(Production p){
        ArrayList<Simbolo> prim = new ArrayList<>();
        Simbolo first = p.getPrimero();
        if(!arrayContains(noTerms, first)){
            prim.add(first);
        }else{
            int index = noTerms.indexOf(symbolOf(noTerms, first));
            for (Simbolo get : primero.get(index)) {
                prim.add(get);
            }
        }
        return prim;
    }
    
    //Verificar si Alpha deriva a Epsilon en 0 o mas pasos
    public  boolean verifySgte(Production p){
        for (int i = 1; i < p.getProd().size(); i++) {
            if(arrayContains(noTerms, p.getSimbolo(i))){
                if(!arrayContains(primero.get(noTerms.indexOf(symbolOf(noTerms, p.getSimbolo(i)))), EPS)){
                    return false;
                }
            }else{
                return false;
            }
        }
        return true;
    }
    
    //Obtener Tabla M (Error?)
    public  void getMTable(){
        int fil = noTerms.size();
        int col = terms.size();
        mTable = new Production[fil][col];
        for (int i = 0; i < fil; i++) {
            for (int j = 0; j < col; j++) {
                mTable[i][j] = new Production();
            }
        }
        for (int i = 0; i < prods.size(); i++) {
            ArrayList<Production> prod = prods.get(i);
            for (Production prod1 : prod) {
                ArrayList<Simbolo> prim = primProd(prod1);
                if(!arrayContains(prim, EPS)){
                    for (Simbolo prim1 : prim) {
                        int index = terms.indexOf(symbolOf(terms, prim1));
                        mTable[i][index] = prod1;
                    }
                }else{
                    if(verifySgte(prod1)){
                        ArrayList<Simbolo> sgte = siguiente.get(i);
                        for (Simbolo sgte1 : sgte) {
                            int index = terms.indexOf(symbolOf(terms, sgte1));
                            mTable[i][index] = prod1;
                        }
                    }else{
                        for (Simbolo prim1 : prim) {
                            if(!prim1.getSimbolo().equals(EPS.getSimbolo())){
                                int index = terms.indexOf(symbolOf(terms, prim1));
                                mTable[i][index] = prod1;
                            }
                        }
                    }
                }
            }
        }
    }
    
    //Obtener Tabla M (Non So?)
    public  void getMTable2(){
        int fil = noTerms.size();
        int col = terms.size();
        mTable = new Production[fil][col];
        for (int i = 0; i < fil; i++) {
            for (int j = 0; j < col; j++) {
                mTable[i][j] = new Production();
            }
        }
        for (int i = 0; i < prods.size(); i++) {
            ArrayList<Production> prod = prods.get(i);
            for (Production prod1 : prod) {
                ArrayList<Simbolo> prim = primProd(prod1);
                if(arrayContains(prim, EPS)){
                    if(verifySgte(prod1)){
                        ArrayList<Simbolo> sgte = siguiente.get(i);
                        for (Simbolo sgte1 : sgte) {
                            int index = terms.indexOf(symbolOf(terms, sgte1));
                            mTable[i][index] = prod1;
                        }
                    }else{
                        boolean sw = false;
                        int j = 1;
                        while (!sw && j < prod1.getProd().size()) {
                            if(arrayContains(noTerms, prod1.getSimbolo(j))){
                                ArrayList<Simbolo> aux = primero.get(noTerms.indexOf(symbolOf(noTerms, prod1.getSimbolo(j))));
                                if(!arrayContains(aux, EPS)){
                                    for (Simbolo aux1 : aux) {
                                        int index = terms.indexOf(symbolOf(terms, aux1));
                                        mTable[i][index] = prod1;
                                    }
                                    sw = true;
                                }else{
                                    for (Simbolo aux1 : aux) {
                                        if(!aux1.getSimbolo().equals(EPS.getSimbolo())){
                                            int index = terms.indexOf(symbolOf(terms, aux1));
                                            mTable[i][index] = prod1;
                                        }
                                    }
                                }
                            }else{
                                int index = terms.indexOf(symbolOf(terms, prod1.getSimbolo(j)));
                                mTable[i][index] = prod1;
                                sw = true;
                            }
                            j++;
                        }
                    }
                }
                for (Simbolo prim1 : prim) {
                    if(!prim1.getSimbolo().equals(EPS.getSimbolo())){
                        int index = terms.indexOf(symbolOf(terms, prim1));
                        mTable[i][index] = prod1;
                    }
                }
            }
        }
    }
    
    //Imprimir Tabla M
    public  void printMTable(){
        int fil = noTerms.size();
        int col = terms.size();
        System.out.println("Tabla M");
        for (int i = 0; i < fil; i++) {
            String out = "";
            for (int j = 0; j < col-1; j++) {
                out += mTable[i][j].toString() + " \t| ";
            }
            out += mTable[i][col-1];
            System.out.println(out);
        }
        System.out.println("");
    }
    
    public  void tableGraphics(){
        
        //Dibujar Tabla                
        //DefaultTableModel tm = (DefaultTableModel) Grid.getModel();
        DefaultTableModel tm = new DefaultTableModel();
        tm.setColumnCount(terms.size()+1);
        tm.setRowCount(noTerms.size());
        Grid.setModel(tm);
        JTableHeader tableHeader = Grid.getTableHeader();
        TableColumnModel tableColumnModel = tableHeader.getColumnModel();
        TableColumn tableColumn = tableColumnModel.getColumn(0);
        tableColumn.setHeaderValue("");
        
        for (int k=1; k < tm.getColumnCount(); k++){
            tableColumn = tableColumnModel.getColumn(k);
            tableColumn.setHeaderValue(terms.get(k-1));
            //tableColumn.sizeWidthToFit();
        }
        tableHeader.repaint();
        
        for(int z=0; z<noTerms.size(); z++){
            Grid.setValueAt(noTerms.get(z), z, 0);
        }
        
        
        int fil = noTerms.size();
        int col = terms.size();
        for (int i = 0; i < fil; i++) {
            for (int j = 0; j < col; j++) {
                String out = "";
                if(!mTable[i][j].getProd().isEmpty()){
                    out += noTerms.get(i).getSimbolo() + " -> " + mTable[i][j].toString();
                }
                //Reemplazar la sgte linea por la asignacion en la celda del jTable (Se asigna out)
                System.out.println("M[" + noTerms.get(i).getSimbolo() + ", " + terms.get(j).getSimbolo() + "] = " + out);
                Grid.setValueAt(out, i, j+1);
            }
        }
        System.out.println(""); //Quitar
        columnFitter();
    }
    
    public void columnFitter(){
        for (int column = 0; column < Grid.getColumnCount(); column++)
        {
            TableColumn tableColumn = Grid.getColumnModel().getColumn(column);
            int preferredWidth = tableColumn.getMinWidth();
            int maxWidth = tableColumn.getMaxWidth();

            for (int row = 0; row < Grid.getRowCount(); row++)
            {
                TableCellRenderer cellRenderer = Grid.getCellRenderer(row, column);
                Component c = Grid.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + Grid.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width);

                //  We've exceeded the maximum width, no need to check other rows

                if (preferredWidth >= maxWidth)
                {
                    preferredWidth = maxWidth;
                    break;
                }
            }
            tableColumn.setPreferredWidth( preferredWidth );
        }

    }
    
    //Realiza Identificacion de Cadenas
    public ArrayList<String> identify(String cad){
        
        ArrayList<String> salida = new ArrayList<String>();
        boolean sw = true;
        String entr = cad + "$";
        ArrayList<Simbolo> pila = new ArrayList<>();
        pila.add(END);
        pila.add(noTerms.get(0));
        System.out.println("Pila | Entrada | Salida");
        salida.add("Pila | Entrada | Salida");
        while(sw && !getLastSymbol(pila).equals(END.getSimbolo())){
            String sal = "";
            String dataPila = "";
            for (Simbolo pila1 : pila) {
                dataPila += pila1.getSimbolo();
            }
            String copyEntr = entr;
            if(arrayContains(noTerms, getLast(pila))){
                if(arrayContains(terms, new Simbolo("" + entr.charAt(0), false))){
                    Production aux = mTable[noTerms.indexOf(symbolOf(noTerms, getLast(pila)))][terms.indexOf(symbolOf(terms, new Simbolo("" + entr.charAt(0), false)))];
                    if(!aux.getProd().isEmpty()){
                        sal = getLastSymbol(pila);
                        pila.remove(pila.size()-1);
                        if(!aux.getPrimero().getSimbolo().equals(EPS.getSimbolo())){
                            for (int i = aux.getProd().size()-1; i >= 0; i--) {
                                pila.add(aux.getSimbolo(i));
                            }
                        }
                        sal += " -> " + aux.toString();
                    }else{
                        sal = "Error";
                        sw = false;
                    }
                }else{
                    sal = "Error";
                    sw = false;
                }
            }else if(getLastSymbol(pila).equals("" + entr.charAt(0))){
                pila.remove(pila.size()-1);
                entr = entr.substring(1, entr.length());
            }else{
                sal = "Error";
                sw = false;
            }
            System.out.println(dataPila + " | " + copyEntr + " | " + sal);
            salida.add(dataPila + " | " + copyEntr + " | " + sal);
        }
        if(sw){
            String dataPila = "";
            for (Simbolo pila1 : pila) {
                dataPila += pila1.getSimbolo();
            }
            System.out.println(dataPila + " | " + entr + " | Aceptar");
            salida.add(dataPila + " | " + entr + " | Aceptar");
        }
        return salida;
    }
    
    //Obtener Ultimo Simbolo
    public  Simbolo getLast(ArrayList<Simbolo> arr){
        return arr.get(arr.size()-1);
    }
    
    //Obtener Ultimo String
    public  String getLastSymbol(ArrayList<Simbolo> arr){
        return arr.get(arr.size()-1).getSimbolo();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DirField;
    private javax.swing.JTable Grid;
    private javax.swing.JTextField InputField;
    private javax.swing.JTextArea TGramaticas;
    private javax.swing.JTextArea TPrimSig;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}

